#ifndef DRA_COUNTER_MY_COUNTER_H
#define DRA_COUNTER_MY_COUNTER_H
#define DRA_COUNTER_MY_COUNTER_DIGIT_0_VALUE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_1_VALUE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_2_VALUE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_3_VALUE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_4_VALUE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_0_UPDATE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_1_UPDATE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_2_UPDATE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_3_UPDATE 0
#define DRA_COUNTER_MY_COUNTER_DIGIT_4_UPDATE 0
#ifndef DRA_COUNTER_CAT_DEFINED
#define DRA_COUNTER_CAT_DEFINED
#define DRA_COUNTER_CAT_INTERNAL(x0, x1) x0##x1
#define DRA_COUNTER_CAT_1(x0) x0
#define DRA_COUNTER_CAT_2(x0, x1) DRA_COUNTER_CAT_INTERNAL(x0, x1)
#define DRA_COUNTER_CAT_3(x0, x1, x2) DRA_COUNTER_CAT_2(x0, DRA_COUNTER_CAT_2(x1, x2))
#define DRA_COUNTER_CAT_4(x0, x1, x2, x3) DRA_COUNTER_CAT_2(x0, DRA_COUNTER_CAT_3(x1, x2, x3))
#define DRA_COUNTER_CAT_5(x0, x1, x2, x3, x4) DRA_COUNTER_CAT_2(x0, DRA_COUNTER_CAT_4(x1, x2, x3, x4))
#endif
#define MY_COUNTER (DRA_COUNTER_CAT_5(1, DRA_COUNTER_MY_COUNTER_DIGIT_4_VALUE, DRA_COUNTER_MY_COUNTER_DIGIT_2_VALUE, DRA_COUNTER_MY_COUNTER_DIGIT_1_VALUE, DRA_COUNTER_MY_COUNTER_DIGIT_0_VALUE) - DRA_COUNTER_CAT_5(1, 0, 0, 0, 0))
#endif
